# Generated by Django 5.0.3 on 2024-04-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='марка авто')),
            ],
        ),
        migrations.CreateModel(
            name='Car_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='модель авто')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='стоимость минуты поездки')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6, verbose_name='номер авто')),
                ('fuel', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='количество топлива')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='долгота')),
                ('is_available', models.BooleanField(verbose_name='доступна?')),
                ('car_brand', models.ManyToManyField(related_name='Car_brad', to='api.car_brand', verbose_name='марка авто')),
                ('car_model', models.ManyToManyField(related_name='Car_model', to='api.car_model', verbose_name='модель авто')),
                ('plan', models.ManyToManyField(related_name='Plan', to='api.plan', verbose_name='тариф')),
            ],
        ),
    ]
