# Generated by Django 5.0.3 on 2024-04-01 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='plan',
        ),
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.car_brand', verbose_name='марка авто'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.car_model', verbose_name='модель авто'),
        ),
        migrations.AddField(
            model_name='car',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.plan', verbose_name='тариф'),
        ),
    ]
